[project]
name = "odet"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "typer==0.9.0",
    "marko==2.0.0",
    "jinja2==3.1.2",
    "tinydb==4.8.0",
    "openai==0.28.0",
    "pydantic==2.3.0",
    "fastapi==0.103.1",
    "uvicorn==0.23.2",
    "sqlalchemy==2.0.20",
    "platformdirs==3.10.0",
    "python-multipart==0.0.6",
    "gitignore-parser==0.1.6",
    "typing-extensions==4.8.0",
    "frictionless[ckan,csv,excel,json,github,pandas,sql,zenodo]==5.15.10",
]

[tool.setuptools]
packages=["server"]

[tool.hatch.version]
path = "package.json"
pattern = '"version": "(?P<version>.*)"'

[tool.hatch.envs.default]
python = "3.10"
dependencies = [
    "ruff",
    "httpx",
    "isort",
    "black",
    "pytest",
    "neovim",
    "fsspec",
    "pyright==1.1.317",
    "ipython",
    "pytest-cov",
    "pytest-vcr",
    "pytest-mock",
    "pytest-only",
    "pytest-dotenv",
    "pytest-timeout",
    "pytest-lazy-fixture",
]

[tool.hatch.envs.default.scripts]
build = [
  "python -m example.build",
  "python -m runner.build",
  "python -m server.build",
]
check = [
  "pyright server",
]
format = [
  "ruff server --fix",
  "isort server",
  "black server",
]
lint = [
  "ruff server",
  "isort server --check",
  "black server --check",
]
spec = [
  "pytest --cov server --cov-report term-missing --cov-report html:coverage --cov-fail-under 70 --timeout=300",
]
# TODO: support autoreloading and providing a custom folder/port
start = [
  "python -m server",
]
test = [
  "hatch run lint",
  "hatch run check",
  "hatch run spec",
]

[tool.black]
line-length = 90

[tool.isort]
profile = "black"
multi_line_output = 9

[tool.ruff]
line-length = 90
ignore = ["E501", "E731"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.pytest.ini_options]
testpaths = ["server"]
env_files = [".env"]
markers = ["ci: integrational tests (select with '--ci')"]

[tool.pyright]
strict = ["server"]
include = ["server"]
ignore = ["**/__init__.py", "**/__spec__/**/*", "**/conftest.py"]
