[project]
name = "fdapp"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "typer>=0.9",
    "marko>=1.0",
    "tinydb>=4.7",
    "openai>=0.27",
    "pydantic>=2.0",
    "fastapi>=0.78",
    "uvicorn>=0.17",
    "sqlalchemy>=2.0",
    "platformdirs>=3.8",
    "python-multipart>=0.0",
    "typing-extensions>=4.3",
    "gitignore-parser>=0.1",
    "frictionless[ckan,csv,excel,json,pandas,sql]>=5.15.5",
]

[tool.hatch.version]
path = "package.json"
pattern = '"version": "(?P<version>.*)"'

[tool.hatch.envs.default]
dependencies = [
    "ruff",
    "httpx",
    "isort",
    "black",
    "pytest",
    "neovim",
    "pyright==1.1.317",
    "ipython",
    "pytest-cov",
    "pytest-vcr",
    "pytest-mock",
    "pytest-only",
    "pytest-dotenv",
    "pytest-timeout",
    "pytest-lazy-fixture",
    "mkdocs-material",
]

[tool.hatch.envs.default.scripts]
# TODO: support autoreloading and providing a custom folder/port
start = [
  "python -m src.server",
]
docs = [
  "mkdocs build",
]
write = [
  "mkdocs serve",
]
format = [
  "ruff src/server test/server --fix",
  "isort src/server test/server",
  "black src/server test/server",
]
lint = [
  "ruff src/server test/server",
  "isort src/server test/server --check",
  "black src/server test/server --check",
  "pyright src/server test/server",
]
test = [
  "hatch run lint",
  "pytest --cov src/server --cov-report term-missing --cov-report html:coverage --cov-fail-under 70 --timeout=300",
]

[tool.black]
line-length = 90

[tool.isort]
profile = "black"
multi_line_output = 9

[tool.ruff]
line-length = 90
ignore = ["E501", "E731"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.pytest.ini_options]
testpaths = ["test/server"]
env_files = [".env"]
markers = ["ci: integrational tests (select with '--ci')"]

[tool.pyright]
strict = ["src/server"]
include = ["src/server", "test/server"]
ignore = ["**/__init__.py"]
