[project]
name = "frictionless-application"
version = '0.0.0'
dependencies = [
    "tinydb>=4.7",
    "fastapi>=0.78",
    "uvicorn>=0.17",
    "python-multipart>=0.0",
    "frictionless[ckan,csv,excel,json,sql]>=5.14",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "isort",
    "black",
    "pytest",
    "pyright",
    "ipython",
    "livemark",
    "pytest-cov",
    "pytest-vcr",
    "pytest-mock",
    "pytest-only",
    "pytest-dotenv",
    "pytest-timeout",
    "pytest-lazy-fixture",
]

[tool.black]
line-length = 90

[tool.isort]
profile = "black"
multi_line_output = 9

[tool.ruff]
line-length = 90
ignore = ["E501", "E731"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.pytest.ini_options]
testpaths = ["test/server"]
env_files = [".env"]
markers = ["ci: integrational tests (select with '--ci')"]

[tool.pyright]
strict = ["**/*.*"]
include = ["src/server", "test/server"]
ignore = ["**/__init__.py"]
