# Config

system:
  - System
  - https://framework.frictionlessdata.io/docs/framework/dialect.html
  - File dialect concept give us an ability to manage table header and any details related to specific formats.

project:
  - Project
  - https://framework.frictionlessdata.io/docs/framework/dialect.html
  - File dialect concept give us an ability to manage table header and any details related to specific formats.
