name: Create DMG
on: [push]

jobs:
  on-push:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install pyinstaller==6.11.1
          brew install create-dmg
      - name: Build and notarize the dmg file
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_LINK_PASSWORD: ${{ secrets.CSC_LINK_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          chmod +x create-dmg.sh
          ./create-dmg.sh
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distribution-files-macos
          path: |
            *.dmg
          retention-days: 14
